[package]
name = "retry"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "retry"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
